language: node_js
node_js:
  - 9
  - 8
before_install:
  - sudo apt-get update -q
  - sudo apt-get install gcc g++ build-essential checkinstall -y
  - wget http://www.imagemagick.org/download/ImageMagick.tar.gz && mkdir im && tar xvzf ImageMagick.tar.gz -C im --strip-components=1 && (cd im && ./configure && make)
  - (cd im && sudo make install && sudo ldconfig /usr/local/lib && sudo ln -sf /usr/local/bin/convert /usr/bin/convert)
  - mv im ~/
